### ISSUE TITLE
Uploaded video not entering `conversion` state, stuck on `uploading`

### ISSUE THREAD

**Issue by ukudala** [vimeo/VIMUpload#13]
Upon completion of an upload to Vimeo (via VIMNetworking 5.5.5), the uploaded video is entering a `uploading` state (which our project has never experienced before). Previously, our app would upload the video without the Vimeo site showing any indication that the video was uploading; once uploaded, the video went straight to the `conversion` UI, followed by SD availability, HD availability.

I am confident that the video has finished uploading, however we now see this `uploading` state UI, which does not dismiss itself after any length of time:

![screen shot 2015-10-27 at 8 04 09 pm](https://cloud.githubusercontent.com/assets/10834575/10778005/e689c994-7ce6-11e5-8279-356a575a66cd.png)
![screen shot 2015-10-27 at 8 03 20 pm](https://cloud.githubusercontent.com/assets/10834575/10778006/e69f82b6-7ce6-11e5-9ed9-e1ab6a4921fd.png)
![screen shot 2015-10-27 at 8 03 53 pm](https://cloud.githubusercontent.com/assets/10834575/10778007/e6a12c60-7ce6-11e5-9be3-aad760b77103.png)

> That's a pretty long upload

@alfiehanssen

**Comment by alfiehanssen** [comment]
Thanks @ukudala, 

If you have a moment, wondering if this branch resolves the issue you're seeing: 

https://github.com/vimeo/VIMUpload/pull/12

**Comment by alfiehanssen** [comment]
cc @ghking

**Comment by ukudala** [comment]
Hi @alfiehanssen - the issue seems to be stemming from VIMNetworking's completion handler. We took @ghking's and put them into VIMNetworking, however the upload behaved correctly for both pre-and-post `ghking` changes. 

When the upload completes in the background, the video's get stuck on the `Uploading` screen in Vimeo video webpage.

<img width="1025" alt="screen shot 2015-10-29 at 8 34 50 am" src="https://cloud.githubusercontent.com/assets/10834575/10821427/03a92f56-7e18-11e5-9e7c-b373232bcaed.png">

> https://vimeo.com/user37760602/review/143998005/2d1d35f9f7

**Comment by ukudala** [comment]
I should note that when testing background uploads the app is brought to the foreground after upload completion to assist in VIMNetworking completion tasks.

> Further indicating a bug in the completion handler, as system resources are fully available at this point to complete required tasks

**Comment by ukudala** [comment]
##### Regarding this

If you leave the `uploading` page displayed, eventually an error will be presented and the video removed:

<img width="987" alt="image" src="https://cloud.githubusercontent.com/assets/10834575/10840045/8f457f96-7ea0-11e5-94e9-553fd5783907.png">

**Comment by ukudala** [comment]
Closing in favor of ticket #14
