### ISSUE TITLE
Background uploads fail

### ISSUE THREAD

**Issue by ukudala** [vimeo/VIMUpload#14]
When using VIMUpload `1.1.1` on [branch `5.6.1`](https://github.com/vimeo/VIMUpload/commit/d1c030ff6201bd25c8b443668d33bd6211b6b21c), uploads made in the foreground will complete successfully and immediately enter 'Conversion' state on Vimeo video web view. This demonstrates that upload is working correctly; after video conversion process takes place video is available to stream.

Unfortunately, video uploads completed while the app is backgrounded will, upon upload, get stuck on Vimeo's `Uploading` video web view state. According to this forum post, it means that the upload has failed:
https://vimeo.com/forums/help/topic:70636

If a video upload process is put into the background, then app returns to foregrounded allowing video to complete in the foreground, the video will successfully enter the `Conversion` state. This tells us that there is something going on with background uploads in VIMUpload 1.1.1 that was not resolved via branch https://github.com/vimeo/VIMUpload/commit/d1c030ff6201bd25c8b443668d33bd6211b6b21c

**Comment by alfiehanssen** [comment]
Additional background context: @ukudala is not running into quota breech issues. The uploading account is either Plus or Pro. The videos are large, upwards of 1GB. The app successfully completes all steps necessary for an upload (the app thinks that the upload finished successfully). 

@dinasolovey can reproduce this issue in-house. 

cc @Dashron @vayam

**Comment by alfiehanssen** [comment]
@dinasolovey Can you post the links to the videos that you uploaded and are stuck in the "uploading" state?

**Comment by dinasolovey** [comment]
@alfiehanssen  here they are (the "stuck" ones):
https://vimeo.com/144678621
https://vimeo.com/144684248

this one was successful though - https://vimeo.com/144680229

**Comment by ukudala** [comment]
@alfiehanssen thank you to the Vimeo crew for taking care of this; looks to be resolved for me :boom:

**Comment by alfiehanssen** [comment]
Wonderful!

On Nov 12, 2015, at 1:23 PM, ukudala <notifications@github.com<mailto:notifications@github.com>> wrote:

@alfiehanssenhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_alfiehanssen&d=CwMCaQ&c=r30hyXAdWe8oret4PlAIyA&r=z0-F0F5oYruJL3Se99qmCA&m=tR-r5EZZ3hPxckyjg52cskUjTprOI35Q1F7-8rhy_w4&s=JqW0LWpNVR23mds4D0p7O6kvToeFc-yKIFOKd13MWoE&e= thank you to the Vimeo crew for taking care of this; looks to be resolved for me [:boom:]
