### ISSUE TITLE
VIMAPIClient

### ISSUE THREAD

**Issue by pcardoso** [vimeo/VIMUpload#17]
Where can I find the VIMAPIClient class?

I see references to it in several places, the Pegasus app uses it, but I can't seem to find it anywhere.

Any pointers? Thanks

**Comment by alfiehanssen** [comment]
@pcardoso Just updated the README on the v6.0.0 branch to explain. This class is part of [VIMNetworking](https://github.com/vimeo/VIMNetworking).
