### ISSUE TITLE
Upload issues; stuck in uploading state; uploaded from background

### ISSUE THREAD

**Issue by ukudala** [vimeo/VIMUpload#18]
@alfiehanssen 

Stuck in uploading bug from tickets #13 , #14 seem to have appeared again:
##### Effected video URLs
- https://vimeo.com/147706136
- https://vimeo.com/147699810

_Please note, these uploads were completed while the application using VIMUpload was in the background. It seems this issue is still at large._

cc from previous tickets @Dashron @vayam @dinasolovey 

![screen shot 2015-12-03 at 8 13 02 am](https://cloud.githubusercontent.com/assets/10834575/11564294/b5cbc084-9995-11e5-8959-ba139ff9c684.png)

**Comment by alfiehanssen** [comment]
@ukudala Thanks for filing this issue, our backend team resolved it last week.
