### ISSUE TITLE
Subclass of "VIMTaskQueue" does not have  "initWithSessionManager" method

### ISSUE THREAD

**Issue by pramodsharma403** [vimeo/VIMUpload#19]
![customvim_h](https://cloud.githubusercontent.com/assets/5866845/11625220/2f75fc08-9cff-11e5-82fa-424a66724468.png)
![customvim_m](https://cloud.githubusercontent.com/assets/5866845/11625221/2f799c0a-9cff-11e5-8b5a-f6bfb2494d3e.png)

**Comment by alfiehanssen** [comment]
Please provide more detail.

**Comment by pramodsharma403** [comment]
@alfiehanssen  I followed document to create subclass of **_VIMTaskQueue**_ but getting error with initWithSessioManager method. You can see screen shot attached in previous comment.

**Comment by NarendraPunchh** [comment]
Getting the same issue with pod 'VIMUpload', '1.0.0'.

**Comment by pramodsharma403** [comment]
@alfiehanssen any help here ?

**Comment by alfiehanssen** [comment]
Typo :( 

I just updated the README on branch `v6.0.0`. It was meant to say "Subclass `VIMUploadTaskQueue`..."

Apologies!
