### ISSUE TITLE
NSAppTransportSecurity Not Allowing Upload

### ISSUE THREAD

**Issue by ChristopherCarranza** [vimeo/VIMUpload#22]
Trying to get the upload library working in my iOS 9 app. I have it working if i set app transport security to "allow arbitrary loads", but i can't get it to work if i try to write an exception for vimeo. I've tried to allow vimeo.com and its subdomains but it still gets blocked. Not sure if it has something to do with the upload address starting with a series of numbers? 

example: https://1511923769.cloud.vimeo.com

I know ATS doesn't allow IP addresses as excepted domains. Anyways if someone has this working i'd love to know what i'm supposed to put to allow this to work. I'll only use allow arbitrary loads if i absolutely have to.

**Comment by alfiehanssen** [comment]
I don't know of a way to do this without (1) allowing arbitrary loads and (2) creating exceptions for a specific set of domains (like api.vimeo.com). Later this year we may introduce some upload server changes that would allow us to further restrict arbitrary loads.
