### ISSUE TITLE
Video upload stopped working

### ISSUE THREAD

**Issue by iamabhiee** [vimeo/VIMUpload#24]
In our iOS application, we are using video upload with VIMUpload(https://github.com/vimeo/VIMUpload) it was working fine till some days back but it suddenly stopped working for us

In code we are observing observeValueForKeyPath for UploadStateContext but it is not giving any callback when state changes so our app is constantly in progress state

Can you help us in fixing this?

**Comment by alfiehanssen** [comment]
If it "just stopped working" then it sounds like a server-side issue (we haven't made any updates to the library recently). Are you still seeing this problem?

Also, VIMUpload is no longer being supported. Going forward, [VimeoUpload](https://github.com/vimeo/VimeoUpload) is our defacto, ever-supported, Swift library.
