### ISSUE TITLE
Can't build with Cocoapods and Swift 2 (AFNetworking missing file)

### ISSUE THREAD

**Issue by lgfaria** [vimeo/VIMUpload#8]
So when I try importing the VIMUpload module (using Cocoapods) in a Swift file, it won't build. Is this a bug? I can import whatever Obj-C pod and it builds fine, but can't seem to make this one work.
Thanks

![screen shot 2015-10-19 at 4 41 06 pm](https://cloud.githubusercontent.com/assets/1796159/10587561/654882c4-7680-11e5-97ad-2a19aacf5f35.png)

**Comment by alfiehanssen** [comment]
Hey @lgfaria, we've had some issues with Cocoapods, AFNetworking, and upgrading to Xcode 7 / Swift 2. Mostly related to our internal setup. 

We should have things back to normal shortly. 

Also, we're putting together a pure Swift version of the upload library which leverages a simplified workflow. Stay tuned for those.
